disasters/urls.py
from django.urls import include, path
from . import views

app_name='chat'

urlpatterns = [
    path('kerala_floods/', views.Kerala_FloodsView, name='kerala_floods'),
    path('cyclone_titli/', views.Cyclone_TitliView, name='cyclone_titli'),
    path('indonesian_tsunami/', views.Indonesian_TsunamiView, name='indonesian_tsunami'),
    path('hurricane_michael/', views.Hurricane_MichaelView, name='hurricane_michael'),
]

found/urls.py
from django.urls import path, include
from . import views
from django.conf import settings

app_name = 'found'
urlpatterns = [
    path('kerala_floods/', views.KeralaFloods, name = 'kerala_floods'),
    path('hurricane_michael/', views.HurricaneMichael, name='hurricane_michael'),
    path('cyclone_titli/', views.CycloneTitli, name='cyclone_titli'),
    path('indonesian_tsunami/', views.IndonesianTsunami, name='indonesian_tsunami'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'
urlpatterns = [
    path('', views.HomePageView, name='home'),
    path('home/', views.HomePageView),
    path('about/', views.AboutView, name='about'),
    path('contact/', views.ContactView, name='contact'),
    path('predictions/', views.PredictionsView, name='predictions'),
    path('found/', views.FoundView, name='found'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saathi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('disasters/', include('disasters.urls')),
    path('found/', include('found.urls'))
]

disasters/models.py
from django.db import models

# Create your models here.

found/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from datetime import datetime

class Disasters(models.Model):
    title = models.CharField(max_length=30, blank=False)
    body = models.CharField(max_length=100, blank=False)
    author = models.CharField(max_length=15, blank=False)
    date_published = models.DateTimeField(default=datetime.now, blank=False)
    link = models.CharField(max_length=100, blank=True)

class Feedback_form(models.Model):
    sender = models.EmailField()
    message = models.CharField(max_length=150)

class Prediction(models.Model):
    title = models.CharField(max_length=30, blank=False)
    body = models.CharField(max_length=100, blank=False)
    link = models.CharField(max_length=100, blank=True)

class PersonFound(models.Model):
    my_choices = (
        ("KL","Kerala Floods"),
        ("HM","Hurrincane Micheal"),
        ("CT","Cyclone Titli"),
        ("IT","Indonesian Tsunami"),
    )
    contact = models.CharField(max_length=12, blank=True)
    disaster = models.CharField(max_length=50, blank=False, default='KL', choices=my_choices)
    address = models.CharField(max_length=255, blank=False)
    photo = models.ImageField(upload_to='found/', blank=False)
    uploaded_on = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms
from .models import Feedback_form
from .models import PersonFound

class Feedback(forms.ModelForm):

    class Meta:
        model = Feedback_form
        fields = ('sender', 'message')

class Found(forms.ModelForm):

    class Meta:
        model = PersonFound
        fields = ('contact', 'disaster', 'address', 'photo',)

disasters/views.py
from django.shortcuts import render

def Kerala_FloodsView(request):
    template_name = 'disasters/kerala_floods.html'
    return render(request, template_name)

def Indonesian_TsunamiView(request):
    template_name = 'disasters/indonesian_tsunami.html'
    return render(request, template_name)

def Cyclone_TitliView(request):
    template_name = 'disasters/cyclone_titli.html'
    return render(request, template_name)

def Hurricane_MichaelView(request):
    template_name = 'disasters/hurricane_michael.html'
    return render(request, template_name)

found/views.py
from django.shortcuts import render
from main.models import PersonFound

def KeralaFloods(request):
    template_name = 'Found/kerala_floods.html'
    HM = PersonFound.objects.filter(disaster='KL')

    context = {'HM_data':HM}
    return render(request, template_name, context)

def HurricaneMichael(request):
    template_name = 'Found/hurricane_michael.html'
    HM = PersonFound.objects.filter(disaster='HM')
    context = {'HM_data': HM}
    return render(request, template_name, context)

def CycloneTitli(request):
    template_name = 'Found/cyclone_titli.html'
    HM = PersonFound.objects.filter(disaster='CT')
    context = {'HM_data': HM}
    return render(request, template_name, context)

def IndonesianTsunami(request):
    template_name = 'Found/indonesian_tsunami.html'
    HM = PersonFound.objects.filter(disaster='IT')
    context = {'HM_data': HM}
    return render(request, template_name, context)

main/views.py
from django.shortcuts import render, redirect, HttpResponse
from main.models import Disasters, Prediction
from .forms import Feedback, Found
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
import requests

@csrf_exempt
def HomePageView(request):
    if request.method == 'POST':
        if 'latitude' in request.POST:
            lat = request.POST['latitude']
            lon = request.POST['longitude']
            key = 'yivWcEFmJWKFvIteu_8LluM1uZgauY8oLecRRsYBqFg'
            url = 'https://atlas.microsoft.com/search/address/reverse/json?subscription-key='+key+'&api-version=1.0&query='+lat+','+lon+''
            response = requests.get(url)
            json = response.json()
            text='Latitude:' + lat + '\nLongitude:' + lon + '\nAddress:\n'
            text =text+str(json['addresses'][0]['address'])

            #content = 'Latitude:' + lat + '\nLongitude:' + lon + '\nAddress:\n'
            #content = content + text['streetName'] + ',' + text['municipalitySubdivision'] + ',' + text['municipality'] + ',' + text['country'] + '-' + text['postalCode']

            #...........SEND MAIL............
            subject = 'Distress Signal'
            from_email = settings.EMAIL_HOST_USER
            message = text  # TODO update feedback message to user
            to_list = ['pankaj2000.fideri@gmail.com']
            send_mail(subject, message, from_email, to_list, fail_silently=False)
            return HttpResponse('success')  # if everything is OK
    template_name = 'index.html'
    return render(request, template_name)

def AboutView(request):
    template_name = 'about.html'
    return render(request, template_name)


def ContactView(request):
    if request.method == 'POST':
        form = Feedback(request.POST)
        if form.is_valid():
            sender = form.cleaned_data['sender']
            f_message = form.cleaned_data['message']
            post = form.save(commit=False)

            # ........Sending the email.......
            subject = 'Your response'
            from_email = settings.EMAIL_HOST_USER
            message = 'Thank You for giving us your valuable suggestion.'  # TODO update feedback message to user
            to_list = [sender]
            send_mail(subject, message, from_email, to_list, fail_silently=False)

            subject = 'Feedback from {}'.format(sender)
            from_email = settings.EMAIL_HOST_USER
            message = f_message  # TODO update feedback message to user
            to_list = [settings.EMAIL_HOST_USER]
            send_mail(subject, message, from_email, to_list, fail_silently=False)

            return redirect('main:contact')
    else:
        form = Feedback()
        template_name = 'contact.html'

    return render(request, template_name, {'form': form})

def PredictionsView(request):
    template_name = 'predictions.html'
    context = {'prediction':Prediction.objects.all()}
    return render(request, template_name,context)

def FoundView(request): # TODO Complete the found.html page Write some thing at the top. And include link of the disasters
    if request.method == 'POST':
        form = Found(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main:home')
    else:
        form = Found()
        template_name = 'found.html'
    return render(request, template_name, {'form':form})

found/templates/found.html
{% extends 'layout.html' %}
{% block title %}
    Prediction
{% endblock %}

{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../static/img/people.jpeg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Found</h1>
              <span class="subheading">During rescue operation</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>


{% endblock %}

found/templates/hurricane_michael.html
{% block content %}
    <h1>How are you</h1>
    {% if HM_data %}
        {% for data in HM_data %}
            <h1>{{ data.contact }}</h1>
            {{ data.address }}
        {% endfor %}
    {% endif %}
{% endblock %}

templates/Found/cyclone_titli.html
{% extends 'layout.html'%}

{% block head %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('/static/img/disasters/hurricane_michael3.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Found</h1>
              <span class="subheading">During rescue operation</span>
            </div>
          </div>
        </div>
      </div>
    </header>




    <div class="container">
        <div class="row">
            <div class="row">
            {% if HM_data %}
            {% for data in HM_data %}
                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                    <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title=""
                       data-image="https://images.pexels.com/photos/853168/pexels-photo-853168.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                       data-target="#image-gallery">
                        <p><img class="img-thumbnail"
                             src="{{ data.photo.url }}"
                             alt="Another alt text" align="middle">Address:{{data.address}}<br>
                             {% if data.contact %}
                                Contact:{{data.contact}}
                             {%endif%}</p>
                    </a>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>


<script src="/static/js/found.js"></script>
{% endblock %}

templates/Found/hurricane_michael.html
{% extends 'layout.html'%}

{% block head %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('/static/img/disasters/hurricane_michael3.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Found</h1>
              <span class="subheading">During rescue operation</span>
            </div>
          </div>
        </div>
      </div>
    </header>




    <div class="container">
        <div class="row">
            <div class="row">
            {% if HM_data %}
            {% for data in HM_data %}
                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                    <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title=""
                       data-image="https://images.pexels.com/photos/853168/pexels-photo-853168.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                       data-target="#image-gallery">
                        <p><img class="img-thumbnail"
                             src="{{ data.photo.url }}"
                             alt="Another alt text" align="middle">Address:{{data.address}}<br>
                             {% if data.contact %}
                                Contact:{{data.contact}}
                             {%endif%}</p>
                    </a>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>


<script src="/static/js/found.js"></script>
{% endblock %}

templates/disasters/cyclone_titli.html
{% extends 'layout.html' %}
{% block title %}
    CHAT ROOM
{% endblock %}

{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../static/img/post-sample-image.jpeg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>CYCLONE TITLI</h1>
              <h2 class="subheading">A chat room to extend help to the people affected by Cyclone Titli</h2>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->

        <div class="col-lg-8 col-md-10 mx-auto">

            <iframe width="1100" height="1000" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" allowtransparency="true" src="https://chatroll.com/embed/chat/cyclonetitli?id=-qupdYjHYdu&platform=html"></iframe>


          <!-- Pager -->


    </div>

    <hr>
{% endblock %}

templates/found.html
{% extends 'layout.html' %}
{% block title %}
    Prediction
{% endblock %}


{% block content %}
<style>
h1 {
  font-weight: bold;
  color: #FFDC00;
  font-size: 50px;
}
</style>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../static/img/people.jpeg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Found</h1>
              <span class="subheading">During rescue operation</span>
            </div>
          </div>
        </div>
      </div>
    </header>
<div class="col-lg-1 col-md-10 mx-auto">
    <h1>FORM</h1>
    <br>

</div>
<div align="center">
    <h2>If any missing person is found then fill this form</h2>

</div>
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
          </form>
        </div>
      </div>
</div>
<br>
<br>
<br>
<div class="col-lg-6 col-md-15 mx-auto" >
    <h1>LINKS TO LIST OF PEOPLE RESCUED</h1>
</div>
<br>






<div>

</div>
<div class="container">
      <div class="row">
          <div class="row">
        <div class="col-lg-6 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'found:kerala_floods' %}">
              <h2 class="post-title">
                Kerala Floods
              </h2>
              <h3 class="post-subtitle">
                Link to list of people rescued
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-6 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'found:hurricane_michael' %}">
              <h2 class="post-title">
                Hurricane Michael
              </h2>
              <h3 class="post-subtitle">
                Link to list of people rescued
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-6 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'found:cyclone_titli' %}">
              <h2 class="post-title">
                Cyclone Titli
              </h2>
              <h3 class="post-subtitle">
                Link to list of people rescued
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-6 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'found:indonesian_tsunami' %}">
              <h2 class="post-title">
                Indonesia Tsunami
              </h2>
              <h3 class="post-subtitle">
                Link to list of people rescued
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
          </div>
      </div>
    </div>

    <hr>
<div>

</div>
<div>


</div>

<div align="center">

</div>>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block title %}
    Home
{% endblock %}

{% block head %}
<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
    window.console.log(position.coords.latitude, position.coords.longitude);
    var URL = "{% url 'main:home' %}";
    var data = {'latitude': position.coords.latitude, 'longitude':position.coords.longitude};
    $.post(URL, data, function(response){
        if(response === 'success'){ alert('Help is on the way'); }
        else{ alert('Error! :('); }
    });
}



</script>


<link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/buttons.css" rel="stylesheet">
<link href="/static/css/normalize.css" rel="stylesheet">
<link href="/static/css/vicons-font.css" rel="stylesheet">
{% endblock %}


{% block content %}

<style>
h1 {
  font-weight: bold;
  color: #FFDC00;
  font-size: 110px;
}
</style>


    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../static/img/home-bg.jpeg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
                <div class="box bg-4">

                        <button class="button button--moema button--text-thick button--text-upper button--size-s" onclick = "getLocation();" value="Get Location">HELP!!!</button>

				</div>
              <span class="subheading">Press the help button if you are stuck in a disaster</span>
            </div>
          </div>
          <p id="demo"></p>
        </div>
      </div>
    </header>




<div align="center">
    <h1>CHAT ROOMS</h1>
    <h3>This section provides chat room links to recent disasters. Join the room for extending help to the victims.</h3>
</div>
    <!-- Main Content -->
    <div class="container">
      <div class="row">
          <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'chat:kerala_floods' %}">
              <h2 class="post-title">
                Kerala Floods
              </h2>
              <h3 class="post-subtitle">
                Link to Chat Room
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'chat:hurricane_michael' %}">
              <h2 class="post-title">
                Hurricane Michael
              </h2>
              <h3 class="post-subtitle">
                Link to Chat Room
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'chat:cyclone_titli' %}">
              <h2 class="post-title">
                Cyclone Titli
              </h2>
              <h3 class="post-subtitle">
                Link to Chat Room
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
        <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
            <a href="{% url 'chat:indonesian_tsunami' %}">
              <h2 class="post-title">
                Indonesia Tsunami
              </h2>
              <h3 class="post-subtitle">
                Link to Chat Room
              </h3>
          </div>
          <hr>


          <!-- Pager -->
        </div>
          </div>
      </div>
    </div>

    <hr>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/static/css/clean-blog.min.css" rel="stylesheet">

    {% block head %}
    {% endblock %}

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">SAATH-i</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:predictions' %}">Predictions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:found' %}">Found</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:contact' %}">Feedback</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://www.facebook.com/saa.thi.94651">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.instagram.com/saathi108/?hl=en">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; saathi.com 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/static/js/clean-blog.min.js"></script>

  </body>

</html>

templates/layout_found.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="../found/static/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="../found/static/css/vicons-font.css" />
	<link rel="stylesheet" type="text/css" href="../found/static/css/base.css" />
	<link rel="stylesheet" type="text/css" href="../found/static/css/buttons.css" />

    <!-- Bootstrap core CSS -->
    <link href="../found/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="../found/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="../found/static/css/clean-blog.min.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="index.html">SAATH-i</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:predictions' %}">Predictions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:found' %}">Found</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/found/static/vendor/jquery/jquery.min.js"></script>
    <script src="../found/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/found/static/js/clean-blog.min.js"></script>

  </body>

</html>